### PR TITLE
[feature1] Implemented New features

### PR DESCRIPTION
**Pull request by miles0007**
Reviews Suggestions:
- [x] Check the files and the file formating
- [x] Run all checks

### CODE REVIEW

**Comment by jokercodee** [comment]
Nice Changes!!!

**Review by kavin-karthik-dev — CHANGES_REQUESTED** [review]
Add some commenting to make clear picture

**Review by kavin-karthik-dev — APPROVED** [review]

**Review by kavin-karthik-dev — CHANGES_REQUESTED** [review]
This is not the change what I needed. Please merge the automated branch.

**Review by kavin-karthik-dev — APPROVED** [review]
Nice Job..!!

**Review by kavin-karthik-dev — APPROVED** [review]
Nice Job!!

**Pull request merged**
